services:

    go2rtc:
    image: alexxit/go2rtc:latest
    container_name: go2rtc
    restart: unless-stopped
    ports:
      - "8554:8554"        # RTSP output
      - "1984:1984"        # Web UI/API
    volumes:
      - ./go2rtc/go2rtc.yaml:/config/go2rtc.yaml:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - frigate_net

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
    - 8080:8080
    restart: unless-stopped
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  frigate:
    container_name: frigate
    devices:
    - /dev/dri:/dev/dri
    environment:
      FRIGATE_RTSP_PASSWORD: fG-56lui
      MQTT_HOST: 192.168.1.24
      MQTT_PASSWORD: mosquito
      MQTT_USER: mosquito
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 30s
      test:
      - CMD
      - wget
      - --spider
      - -q
      - http://localhost:5000
      timeout: 10s
    image: ghcr.io/blakeblackshear/frigate:stable
    ports:
    - 5000:5000
    - 8554:8554
    - 8555:8555/tcp
    - 8555:8555/udp
    - 1984:1984
    privileged: true
    restart: unless-stopped
    shm_size: 512mb
    volumes:
    - ./frigate/config.yml:/config/config.yml
    - /media/frigate:/media/frigate
    - /dev/bus/usb:/dev/bus/usb
    - /etc/localtime:/etc/localtime:ro
  grafana:
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
    image: grafana/grafana-oss:latest
    ports:
    - 3000:3000
    restart: unless-stopped
    volumes:
    - grafana_data:/var/lib/grafana
  node-exporter:
    command:
    - --path.procfs=/host/proc
    - --path.sysfs=/host/sys
    - --path.rootfs=/rootfs
    - --collector.filesystem.ignored-mount-points
    - ^/(sys|proc|dev|host|etc)($|/)
    container_name: node-exporter
    image: prom/node-exporter:latest
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /:/rootfs:ro
  prometheus:
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.enable-lifecycle
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    restart: unless-stopped
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - prometheus_data:/prometheus
volumes:
  grafana_data: {}
  prometheus_data: {}
