services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    runtime: nvidia
    network_mode: host
    shm_size: "512m"
    environment:
      TZ: Europe/Paris
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: video
      PLUS_API_KEY: ${FRIGATE_PLUS_API_KEY}
    volumes:
      - ./config.yml:/config
      - ${FRIGATE_MEDIA_PATH:-/mnt/nas/video/frigate}:/media/frigate
      - tmpfs:/tmp/ramdisk
