#!/usr/bin/env bash
# ==============================================================================
# install-frigate-cleanup.sh — one-shot installer for the retention enforcer
# ==============================================================================
# Run with sudo (asks password ONCE, then everything is unattended):
#   sudo bash install-frigate-cleanup.sh
#
# Steps:
#   1. Deploy the updated sudoers file (NOPASSWD for install/cron/logrotate)
#   2. Validate the sudoers file with visudo
#   3. Install the frigate-cleanup.sh binary to /usr/local/bin
#   4. Create /etc/cron.d/frigate-cleanup (daily 03:17)
#   5. Create /etc/logrotate.d/frigate-cleanup (daily, 14-day retention)
#   6. Run a --status report to confirm everything is wired up
# ==============================================================================
set -euo pipefail

REPO_DIR="/home/nghia-phan/AGENTIC_DEVELOPMENT_PROJECTS/APPLICATION-PROJECTS/frigate"
SUDOERS_SRC="$REPO_DIR/sudoers/nghia-phan-frigate"
SUDOERS_DST="/etc/sudoers.d/nghia-phan-frigate"
SCRIPT_SRC="$REPO_DIR/frigate-cleanup.sh"
SCRIPT_DST="/usr/local/bin/frigate-cleanup.sh"
CRON_FILE="/etc/cron.d/frigate-cleanup"
LOGROTATE_FILE="/etc/logrotate.d/frigate-cleanup"

[ "$(id -u)" -eq 0 ] || { echo "ERROR: must run as root (use sudo)"; exit 1; }
[ -f "$SUDOERS_SRC" ] || { echo "ERROR: $SUDOERS_SRC missing"; exit 1; }
[ -f "$SCRIPT_SRC" ] || { echo "ERROR: $SCRIPT_SRC missing"; exit 1; }

echo "=== Step 1/6: Deploy updated sudoers ==="
install -m 0440 -o root -g root "$SUDOERS_SRC" "$SUDOERS_DST"
echo "  -> $SUDOERS_DST (0440 root:root)"

echo "=== Step 2/6: Validate sudoers with visudo ==="
visudo -c -f "$SUDOERS_DST"
echo "  -> syntax OK"

echo "=== Step 3/6: Install frigate-cleanup.sh to /usr/local/bin ==="
install -m 0755 -o root -g root "$SCRIPT_SRC" "$SCRIPT_DST"
echo "  -> $SCRIPT_DST (0755 root:root)"

echo "=== Step 4/6: Create /etc/cron.d/frigate-cleanup (daily 03:17) ==="
cat > "$CRON_FILE" <<'EOF'
# /etc/cron.d/frigate-cleanup — daily retention enforcer for Frigate on Calypso
# Generated by install-frigate-cleanup.sh on 2026-08-05
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MAILTO=""
17 3 * * * root /usr/local/bin/frigate-cleanup.sh --apply >> /var/log/frigate-cleanup.log 2>&1
EOF
chmod 644 "$CRON_FILE"
chown root:root "$CRON_FILE"
echo "  -> $CRON_FILE"

echo "=== Step 5/6: Create /etc/logrotate.d/frigate-cleanup ==="
cat > "$LOGROTATE_FILE" <<'EOF'
# /etc/logrotate.d/frigate-cleanup — keep 14 days of cleanup logs
/var/log/frigate-cleanup.log {
    daily
    rotate 14
    compress
    delaycompress
    missingok
    notifempty
    create 0644 root root
    sharedscripts
}
EOF
chmod 644 "$LOGROTATE_FILE"
chown root:root "$LOGROTATE_FILE"
echo "  -> $LOGROTATE_FILE"

echo "=== Step 6/6: First --status report ==="
/usr/local/bin/frigate-cleanup.sh --status 2>&1 | head -15 || true

echo
echo "=== INSTALL COMPLETE ==="
echo "Verify the cron is registered:"
echo "  cat /etc/cron.d/frigate-cleanup"
echo "Verify the next run is tomorrow 03:17:"
echo "  date"
echo "Manual run:"
echo "  sudo /usr/local/bin/frigate-cleanup.sh --apply"
