homeassistant:
  customize:
    device.home-assistant:
      friendly_name: Home Assistant
      area: unspecified
_meta:
  generated: '2025-10-09T15:44:50.129214+00:00'
  source: /home/nghia-phan/git/nuc-docker-stack/sot/examples/sot.sample.yaml
