mqtt:
  host: 192.168.1.24
  user: mosquito
  password: mosquito

record:
  enabled: true
  retain:
    days: 3
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30

detect:
  enabled: true

ffmpeg:
  input_args: preset-rtsp-restream
  retry_interval: 30

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 5
    objects:
      person: 30  

go2rtc:
  streams:
    allee_sur_le_cote:
      - rtsp://frigate:frigate@192.168.1.24:8554/0cb2b74df743_live
      - ffmpeg:cache=120
      - ffmpeg:analyze_duration=0
      - ffmpeg:video=copy#audio=none#analyze_duration=0
    jardin_devant:
      - rtsp://frigate:frigate@192.168.1.24:8554/10cea9f26407_live
      - ffmpeg:cache=120
      - ffmpeg:analyze_duration=0
      - ffmpeg:video=copy#audio=none#analyze_duration=0
    piscine_vue_toit:
      - rtsp://frigate:frigate@192.168.1.24:8554/0cb2b74f37f3_live
      - ffmpeg:cache=120
      - ffmpeg:analyze_duration=0
      - ffmpeg:video=copy#audio=none#analyze_duration=0
    vue_sur_entree_dev:
      - rtsp://frigate:frigate@192.168.1.24:8554/9c761310bb9c_live
      - ffmpeg:cache=120
      - ffmpeg:analyze_duration=0
      - ffmpeg:video=copy#audio=none#analyze_duration=0
    jardin_arriere:
      - rtsp://frigate:frigate@192.168.1.24:8554/9c761310afad_live
      - ffmpeg:cache=120
      - ffmpeg:analyze_duration=0
      - ffmpeg:video=copy#audio=none#analyze_duration=0
    sonnette_video_wired:
      - rtsp://frigate:frigate@192.168.1.24:8554/343ea4da33f2_live
      - ffmpeg:cache=120
      - ffmpeg:analyze_duration=0
      - ffmpeg:video=copy#audio=none#analyze_duration=0

cameras:
  camera_allee_sur_le_cote:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/allee_sur_le_cote
          roles: [detect, record]
    detect:
      width: 1920
      height: 1080
      fps: 5

  camera_jardin_devant:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/jardin_devant
          roles: [detect, record]
    detect:
      width: 1920
      height: 1080
      fps: 5

  camera_piscine_vue_toit:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/piscine_vue_toit
          roles: [detect, record]
    detect:
      width: 1920
      height: 1080
      fps: 5

  camera_vue_sur_entree_dev:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/vue_sur_entree_dev
          roles: [detect, record]
    detect:
      width: 1920
      height: 1080
      fps: 5

  camera_jardin_arriere:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/jardin_arriere
          roles: [detect, record]
    detect:
      width: 1920
      height: 1080
      fps: 5

  sonnette_video_wired:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sonnette_video_wired
          roles: [detect, record]
    detect:
      width: 1920
      height: 1080
      fps: 5

version: 0.15-1