#!/usr/bin/env python3
"""
export_asus_merlin.py
Generate dnsmasq.conf.add for Asus-Merlin routers from the SoT.

For each device with a MAC + IP it writes:
  dhcp-host=<MAC>,<IP>,<hostname>,infinite
  host-record=<hostname>,<IP>

Usage:
  python3 tools/export_asus_merlin.py sot/sot.yaml -o out/asus-merlin
"""
import argparse, yaml
from pathlib import Path
from datetime import datetime

def load_sot(path: Path):
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    data.setdefault("devices", [])
    return data

def collect_entries(devices):
    entries = []
    for d in devices:
        hn = d.get("hostname")
        if not hn:
            continue
        # gather MACs from interfaces
        macs = []
        for iface in (d.get("interfaces") or []):
            mac = iface.get("mac")
            if mac and mac not in macs:
                macs.append(mac)
        # choose IP: dns.ip_current preferred, fallback to interfaces[*].ip
        ips = []
        dns = d.get("dns") or {}
        if dns.get("ip_current"):
            ips.append(dns["ip_current"])
        for iface in (d.get("interfaces") or []):
            ip = iface.get("ip")
            if ip and ip not in ips:
                ips.append(ip)
        if not ips:
            continue
        ip = ips[0]

        # dhcp-host lines if MACs exist
        for mac in macs:
            entries.append(f"dhcp-host={mac},{ip},{hn},infinite")

        # host-record line (always if we have an IP)
        entries.append(f"host-record={hn},{ip}")

    return entries

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("sot", help="path to SoT YAML")
    ap.add_argument("-o", "--out", required=True, help="output directory")
    args = ap.parse_args()

    sot = load_sot(Path(args.sot))
    devices = sot.get("devices", [])
    entries = collect_entries(devices)

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    outf = out_dir / "dnsmasq.conf.add"

    header = [
        "# Autogenerated from SoT — DO NOT EDIT",
        f"# Generated: {datetime.utcnow().isoformat()}Z",
        "",
    ]
    outf.write_text("\n".join(header + entries) + "\n", encoding="utf-8")
    print(f"[OK] wrote {outf} with {len(entries)} entries.")

if __name__ == "__main__":
    main()
