#!/usr/bin/env python3
"""
export_coredns.py
Reads a SoT YAML (v4/v5) and generates CoreDNS zone files.

- Outputs one zone file for the root (e.g. home.arpa) and optional per-category zones.
- Creates A records for devices that have ip_current or an interface with IP.
- Skips devices without IPs (but you can extend to create CNAMEs if desired).
- Safe if SoT is empty: will still write minimal zone files.

Usage:
  python3 tools/export_coredns.py sot/sot.yaml -o out/coredns
"""
import argparse, sys, yaml
from pathlib import Path
from datetime import datetime

def load_sot(path: Path):
    with path.open('r', encoding='utf-8') as f:
        data = yaml.safe_load(f) or {}
    data.setdefault('meta', {})
    data.setdefault('devices', [])
    data.setdefault('groups', [])
    return data

def gather_records(sot):
    zone_root = sot.get('meta', {}).get('zone_root', 'home.arpa').rstrip('.')
    devices = sot.get('devices', []) or []
    groups  = sot.get('groups', []) or []

    def ips_for_device(d):
        ips = []
        # dns.ip_current first
        dns = d.get('dns') or {}
        if dns.get('ip_current'):
            ips.append(dns['ip_current'])
        # also inspect interfaces list
        for iface in (d.get('interfaces') or []):
            ip = iface.get('ip')
            if ip and ip not in ips:
                ips.append(ip)
        return ips

    # Build records for devices
    records = []
    for d in devices:
        fqdn = d.get('fqdn')
        if not fqdn:
            # If fqdn missing, derive from hostname/category/zone_root if present
            hn = d.get('hostname')
            cat = d.get('category')
            if hn and cat:
                fqdn = f"{hn}.{cat}.{zone_root}"
        if not fqdn:
            continue
        fqdn = fqdn.rstrip('.')
        for ip in ips_for_device(d):
            # Only A records (IPv4). Extend later for AAAA if needed.
            records.append(("A", fqdn, ip))

    # (Optional) groups could have VIPs later; for now we skip unless they have a DNS ip_current
    for g in groups:
        fqdn = g.get('fqdn')
        if not fqdn:
            hn = g.get('hostname'); cat = g.get('category')
            if hn and cat:
                fqdn = f"{hn}.{cat}.{zone_root}"
        if not fqdn:
            continue
        fqdn = fqdn.rstrip('.')
        dns = g.get('dns') or {}
        if dns.get('ip_current'):
            records.append(("A", fqdn, dns['ip_current']))

    return zone_root, records

def write_zone(zone_root: str, records, out_dir: Path):
    out_dir.mkdir(parents=True, exist_ok=True)
    zonefile = out_dir / f"{zone_root}.zone"
    serial = datetime.utcnow().strftime("%Y%m%d%H")
    lines = []
    lines.append(f"; Autogenerated from SoT — DO NOT EDIT\n")
    lines.append(f"$ORIGIN {zone_root}.\n")
    lines.append(f"$TTL 300\n")
    lines.append(f"@   IN  SOA ns.{zone_root}. hostmaster.{zone_root}. (\n")
    lines.append(f"        {serial} ; serial\n")
    lines.append(f"        3600     ; refresh\n")
    lines.append(f"        600      ; retry\n")
    lines.append(f"        604800   ; expire\n")
    lines.append(f"        300 )    ; minimum\n")
    lines.append(f"@   IN  NS  ns.{zone_root}.\n")
    lines.append(f"ns  IN  A   127.0.0.1\n")  # local NS (you can override)

    # records
    for rtype, fqdn, ip in sorted(records, key=lambda x: x[1]):
        # convert FQDN to relative if within zone
        if fqdn.endswith(f".{zone_root}"):
            rel = fqdn[:-(len(zone_root)+1)]
        else:
            rel = fqdn + "."
        if rel == "":
            rel = "@"
        lines.append(f"{rel} IN {rtype} {ip}\n")

    zonefile.write_text("".join(lines), encoding="utf-8")
    print(f"[OK] wrote {zonefile}")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("sot", help="path to SoT YAML (v4/v5)")
    ap.add_argument("-o", "--out", required=True, help="output directory for CoreDNS zones")
    args = ap.parse_args()

    sot = load_sot(Path(args.sot))
    zone_root, records = gather_records(sot)
    write_zone(zone_root, records, Path(args.out))

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(130)
